linters:
  enable:
    - bodyclose
    - canonicalheader
    - cyclop
    - decorder
    - gci
    - goconst
    - gocritic
    - gofmt
    - gosec
    - misspell
    - mnd
    - reassign
    - testifylint
    - zerologlint
issues:
  new-from-rev: HEAD
run:
  tests: false
  modules-download-mode: readonly
