name: Test and Build
on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
    tags:
      - v*

# This ensures that previous jobs for the PR are canceled when the PR is
# updated.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          fail_on_error: true
          go_version_file: go.mod
          reporter: github-pr-review
  test:
    name: test
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: restore cached modules
        uses: actions/cache/restore@v4
        with:
          key: linux-golangci-${{ hashFiles('**/go.sum') }}
          path: |
            ~/.cache/golangci-lint
            ~/.cache/go-build
            ~/go/pkg
      - name: install go-junit-report
        run: |
          curl -sL "https://github.com/jstemmer/go-junit-report/releases/download/v2.1.0/go-junit-report-v2.1.0-linux-amd64.tar.gz" | tar xz
          chmod +x go-junit-report
          mv go-junit-report /usr/local/bin/
      - name: test
        run: |
          make report.xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: set test status
        if: always()
        uses: test-summary/action@v2
        # potentially switch to EnricoMi/publish-unit-test-result-action
        with:
          paths: report.xml
      - name: save test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-status
          path: |
            coverage.html
            report.xml
  build:
    name: build
    runs-on: ubuntu-latest
    needs: test
    strategy:
      fail-fast: false
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64, arm]
        exclude:
          - os: darwin
            arch: arm
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: restore cached modules
        uses: actions/cache/restore@v4
        with:
          key: linux-golangci-${{ hashFiles('**/go.sum') }}
          path: |
            ~/.cache/golangci-lint
            ~/.cache/go-build
            ~/go/pkg
      - name: compile
        env:
          # disable CGO to make fully static binaries
          CGO_ENABLED: 0
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          make all
      - name: save build artifacts
        uses: actions/upload-artifact@v4
        with:
          path: bin/
          name: binaries-${{ matrix.os }}-${{ matrix.arch }}
  buildresult:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Build Result Status
    needs: [build]
    steps:
      - run: exit 1
        if: >-
          ${{
               contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
            || contains(needs.*.result, 'skipped')
          }}
  docker:
    name: docker build
    runs-on: ubuntu-latest
    needs: buildresult
    strategy:
      fail-fast: false
      matrix:
        os: [linux] #, windows, darwin]
        arch: [amd64, arm64, arm]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: restore build artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: binaries-*
          merge-multiple: true
          path: bin/
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}
          flavor: latest=false
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,event=tag,pattern={{version}}
            type=semver,event=tag,pattern={{major}}
            type=sha,event=pr,format=short
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push digest
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            - GOOS=${{ matrix.os }}
            - GOARCH=${{ matrix.arch }}
          platforms: ${{ matrix.os }}/${{ matrix.arch }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=registry,name=${{ github.repository }},push-by-digest=true,name-canonical=true
      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ matrix.os }}-${{ matrix.arch }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1
  dockerresult:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Docker Result Status
    needs: [docker]
    steps:
      - run: exit 1
        if: >-
          ${{
               contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
            || contains(needs.*.result, 'skipped')
          }}
  manifest:
    name: publish docker manifest
    runs-on: ubuntu-latest
    needs:
      - dockerresult
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-*
          merge-multiple: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}
          flavor: latest=false
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,event=tag,pattern={{version}}
            type=semver,event=tag,pattern={{major}}
            type=sha,event=pr,format=short
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ github.repository }}@sha256:%s ' *)
      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ github.repository }}:${{ steps.meta.outputs.version }}
  publish:
    runs-on: ubuntu-latest
    needs:
      - buildresult
    if: github.event_name == 'tag' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: restore build artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: binaries-*
          merge-multiple: true
          path: bin/
      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            bin/*
