name: Test and Build
on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
    tags:
      - v*
jobs:
  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          fail_on_error: true
          go_version_file: go.mod
          reporter: github-pr-review
  test:
    name: test
    runs-on: ubuntu-latest
    needs: golangci-lint
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: test
        run: |
          make coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  build:
    name: build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: compile
        run: |
          make all
