name: Docker build

on:
  workflow_run:
    workflows: [Test and Build]
    types:
      - completed
  push:
    tags:
      # could be triggered by tagging release, which would be of form "v.N.N.N"
      - v*

jobs:
  docker:
    if: github.event.workflow_run.conclusion == 'success'
    uses: aztechian/kube-nut/.github/workflows/docker-build.yaml@main
    with:
      platforms: linux/386,linux/amd64,linux/arm64,windows/amd64,windows/386,darwin/arm64,darwin/386
